spring.data.mongodb.uri: mongodb://localhost:27017/sampledb

# Keycloak configuration properties
#keycloak:
#  realm: fruits-catalog
#  resource: fruits-catalog-app
#  auth-server-url: ${KEYCLOAK_URL:http://localhost:8180/auth}
#  bearer-only: true
#  ssl-required: external
#  security-constraints:
#    - authRoles:
#      - user
#      - manager
#      - admin
#    - securityCollections:
#      - name: Insecure stuffs
#        patterns:
#          - /api/fruits

# Metrics related configurations
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# OpenTracing related configurations.
opentracing:
  jaeger:
    enabled: true
    log-spans: true
    enable-b3-propagation: false
    udp-sender:
      host: "localhost"
      port: 5775
